### ISSUE TITLE
Move Styles Under Appropriate Components/Containers

### ISSUE THREAD

**Issue by skellock** [infinitered/react_native_base#23]
The current `Styles` directory doesn't scale well.  Let's move those files to a new home which reflects the ownership.

```
/App/Components/Styles/
/App/Containers/Styles/
```

These components & containers styles are only used by 1 file anyway.

Thanks @GantMan and @kevinvangelder for illuminating this problem.

I'll tackle this one.

**Comment by markrickert** [comment]
:+1:
